name: Run Python Script and Upload CSVs

on:
    workflow_dispatch:
    schedule:
      - cron: "25 * * * *"
      
permissions:
  contents: write  # Grants write access to the repository contents

jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15  # Terminate the job if it exceeds 15 minutes

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify Environment Variables
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          echo "CLIENT_ID: $CLIENT_ID"
          echo "CLIENT_SECRET: $CLIENT_SECRET"

      - name: Execute Python Script
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.REFRESH_TOKEN }}
        run: |
          set -x
          python src/main.py
          
      - name: Commit and Push CSV Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add ./data/*.csv
          git commit -m "Updated CSV files"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload CSV Files
        uses: actions/upload-artifact@v3
        with:
          name: csv-outputs
          path: ./data/*.csv
